config/routes.rb
Rails.application.routes.draw do
  
  get 'product/new'

  get 'company/new'

  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/companies', to: 'company#index'
  get    '/create_company', to: 'company#new'
  post   '/companies', to: 'company#create'
  get    '/api/companies', to: 'company#indexApi'
  get    '/products', to: 'product#index'
  get    '/new_product', to: 'product#new'
  post   '/products', to: 'product#create'
  get    '/api/products', to: 'product#showApi'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :company
  resources :product
 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
 This website was made thanks to that <a href="http://www.railstutorial.org/book">tutorial</a>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
 Contact me by mail, and visit my <a href="http://www.bastien-rolando.com">website</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
  Come on, do you really need help ?
</p>

app/views/static_pages/home.html.erb
</div>
<div class="center">
  <h1>Welcome to Pro-Duct</h1>


  <% if logged_in? %>
  
  <h2>
    Thank you for joining Pro-duct !
  </h2>
  
  <%= link_to "Register products for your company !", new_product_path, class: "btn btn-lg btn-warning" %>
  <% else %>
  
  <h2>
    This website is designed to list the products of any company</br>
    Don't wait and sign up in order to help us in that listing !
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-warning" %>
  
  <% end %>
</div>
</div class="container">